spring:
  datasource:
    primary:
      url: jdbc:postgresql://localhost:5432/inventory
      username: postgres
      password: root
      driver-class-name: org.postgresql.Driver

    secondary:
      jdbcUrl: jdbc:mysql://localhost:3306/inventory?useSSL=false&serverTimezone=UTC
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
   show-sql: true
     ## Hibernate Properties
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
   properties.hibernate.dialect : org.hibernate.dialect.PostgreSQLDialect
    # Hibernate ddl auto (create, create-drop, validate, update)
   hibernate.ddl-auto: update

  mvc:
    path match:
      matching-strategy: ant-path-matcher





