spring:
  datasource:
    primary:
      jdbcUrl: jdbc:postgresql://localhost:5432/inventory
      username: postgres
      password: root
      driver-class-name: org.postgresql.Driver

    secondary:
      jdbcUrl: jdbc:mysql://localhost:3306/inventory?useSSL=false&serverTimezone=UTC
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    path:
      match:
        matching-strategy: ant-path-matcher


logging:
  level:
    root: INFO
    org:
      hibernate: INFO
      springframework: INFO
