#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/laxmiinventory
#    username: postgres
#    password: root
#
#
#  jpa:
#   show-sql: true
#     ## Hibernate Properties
#    # The SQL dialect makes Hibernate generate better SQL for the chosen database
#   properties.hibernate.dialect : org.hibernate.dialect.PostgreSQLDialect
#    # Hibernate ddl auto (create, create-drop, validate, update)
#   hibernate.ddl-auto: update



  mvc:
    path match:
      matching-strategy: ant-path-matcher





